In [0]:
from __future__ import print_function
import torch

In [42]:
x = torch.ones((2,2), requires_grad = True) #create tensor of size 2x2 and tracking gradients
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [43]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [44]:
print(y.grad_fn)

In [45]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [46]:
a = torch.randn(2,2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [0]:
out.backward() #single element, hence no specifying gradient argument

In [48]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [57]:
x = torch.randn(3, requires_grad = True)
y = x * 2
while y.data.norm() < 1000:
  y = y * 2

print(y)

tensor([-921.9027, -357.1745, -640.7955], grad_fn=<MulBackward0>)


In [58]:
v = torch.randn_like(y, dtype = torch.float) #compute gradients by passing v to backward as y is not a single scalar
y.backward(v)
print(x.grad)

tensor([-5858.5610, -6261.3770, -3370.6023])


In [62]:
print(x.requires_grad)
print((x ** 2).requires_grad)
with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


In [64]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)
